fixup! fixup! SystemUI: Fix constraints for keyguard slice view
Ported from Google commit 447d84e6797f71e287f1d3ddc7c99b41881d3047
not knowing whether this fix is correct or not. At least it fixes

frameworks/base/packages/SystemUI/src/com/android/systemui/keyguard/ui/view/layout/sections/KeyguardSliceViewSection.kt:62:69: error: unresolved reference: status_view_margin_horizontal
                    context.resources.getDimensionPixelSize(R.dimen.status_view_margin_horizontal),
                                                                    ^

Change-Id: I70aea3c00399838acedd2fb8d4fbce7c02cc4903